name: Packer Template Validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.pkr.hcl'
      - 'src/**'  # Also trigger on source code changes

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Initialize Packer
        run: |
          cd packer
          packer init .

      - name: Format Check
        run: |
          cd packer
          packer fmt -check .
          if [ $? -ne 0 ]; then
            echo "Packer template not properly formatted"
            exit 1
          fi
        shell: /usr/bin/bash -e {0}

      - name: Modify Packer Template for Validation
        run: |
          cd packer
          # Create a dummy JAR file if needed for validation
          mkdir -p ../target
          touch ../target/webapp-0.0.1-SNAPSHOT.jar || true
          # Alternatively, you could modify the template temporarily for validation

      - name: Validate Template
        run: |
          cd packer
          packer validate .
          if [ $? -ne 0 ]; then
            echo "Packer template validation failed"
            exit 1
          fi
        shell: /usr/bin/bash -e {0}