name: Build Custom Images

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1



      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Initialize Packer
        run: |
          cd packer
          packer init .

      - name: Build Images
        run: |
          # Create temp credentials file from secret
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/gcp-key.json

          cd packer
          packer build .
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json

