name: testci2

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip mysql-server mysql-client openjdk-17-jdk maven

      - name: Configure MySQL
        run: |
          # Stop MySQL if it's running
          sudo systemctl stop mysql
          
          # Start MySQL with temporary settings
          sudo mkdir -p /var/run/mysqld
          sudo chown mysql:mysql /var/run/mysqld
          sudo mysqld --skip-grant-tables --skip-networking &
          sleep 10
          
          # Set root password
          sudo mysql -e "FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED BY 'Saurabh';"
          
          # Restart MySQL normally
          sudo pkill mysqld
          sleep 5
          sudo systemctl start mysql
          sleep 5
          
          # Create database and user
          sudo mysql -uroot -pSaurabh -e "CREATE DATABASE IF NOT EXISTS webapp;"
          sudo mysql -uroot -pSaurabh -e "CREATE USER IF NOT EXISTS 'saurabh'@'%' IDENTIFIED BY 'saurabh';"
          sudo mysql -uroot -pSaurabh -e "GRANT ALL PRIVILEGES ON webapp.* TO 'saurabh'@'%';"
          sudo mysql -uroot -pSaurabh -e "FLUSH PRIVILEGES;"
        shell: /usr/bin/bash -e {0}


      - name: Run Tests
        run: mvn test -Dtest=HealthCheckControllerTest