name: testci3

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Saurabh
          MYSQL_DATABASE: webapp
          MYSQL_USER: saurabh
          MYSQL_PASSWORD: saurabh
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Verify MySQL Connection
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            sleep 1
            echo "Waiting for MySQL to be ready..."
          done
          echo "MySQL is up and running"

      - name: Run Tests
        run: mvn test -Dtest=HealthCheckControllerTest
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/webapp
          SPRING_DATASOURCE_USERNAME: saurabh
          SPRING_DATASOURCE_PASSWORD: saurabh