name: testCI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip mysql-server mysql-client openjdk-17-jdk maven

      - name: Configure MySQL
        run: |
          sudo systemctl enable mysql
          sudo systemctl start mysql
          
          # First, set root password without requiring current password
          sudo mysqld_safe --skip-grant-tables --skip-networking &
          sleep 10
          sudo mysql -e "FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED BY 'Saurabh';"
          sudo killall mysqld
          sleep 10
          sudo systemctl start mysql
          sleep 5
          
          # Now create database and user with the root password
          sudo mysql -u root -pSaurabh -e "CREATE DATABASE IF NOT EXISTS webapp;"
          sudo mysql -u root -pSaurabh -e "CREATE USER IF NOT EXISTS 'saurabh'@'%' IDENTIFIED BY 'saurabh';"
          sudo mysql -u root -pSaurabh -e "GRANT ALL PRIVILEGES ON webapp.* TO 'saurabh'@'%';"
          sudo mysql -u root -pSaurabh -e "FLUSH PRIVILEGES;"
        shell: /usr/bin/bash -e {0}
        env:
          DB_NAME: webapp
          DB_USER: saurabh
          DB_PASSWORD: saurabh
          DB_ROOT_PASSWORD: Saurabh
          APP_GROUP: saurabh_group
          APP_USER: saurabh_user
          APP_DIR: /opt/csye6225

      - name: Setup Application User and Directory
        run: |
          sudo groupadd saurabh_group || true
          sudo useradd -m -g saurabh_group -s /bin/bash saurabh_user || true
          
          sudo mkdir -p /opt/csye6225
          sudo chown saurabh_user:saurabh_group /opt/csye6225
          sudo chmod 750 /opt/csye6225
          
          if [ -f "webapp.zip" ]; then
            sudo unzip -o webapp.zip -d /opt/csye6225
            sudo chown -R saurabh_user:saurabh_group /opt/csye6225
            sudo chmod -R 750 /opt/csye6225
          fi

      - name: Run Tests
        run: mvn test -Dtest=HealthCheckControllerTest